# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 12 * * 3'   # Запуск каждую среду в 12:30
    - cron: '0 22 * * 5'     # Запуск каждую пятницу в 22:00

permissions:
  contents: read

jobs:
  build:

#Добавление блока matrix для указания различных комбинаций версий ОС и версий Java
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest or ubuntu-22.04, ubuntu-20.04, windows-latest or windows-2022, windows-2019, macos-latest or macos-12, macos-11]
        java: [11, 13, 17]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        
    - name: Grant execute permissions to gradlew
      run: chmod +x ./gradlew   
       
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build
